### ISSUE TITLE
Crash on Android 8.x

### ISSUE THREAD

**Issue by selimanac** [GameAnalytics/GA-SDK-DEFOLD#23]
GameAnalytic native extension cause a crash on Android 8.1 but works on 6.1.0. This is because the Defold engine moved core Android libs into separate extension.

Now on users of GA-Defold for Android should include [extension-gps](https://github.com/defold/extension-gps) into their dependencies. I would suggest you to update the documentation like [this project](https://github.com/defold/extension-firebase-analytics#2-defold-setup).

```
E  FATAL EXCEPTION: main
                         E  Process: com.thevogons.matchit, PID: 17472
                         E  java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompat;
                         E      at com.gameanalytics.sdk.GAPlatform.loadIMEI23AndAbove(GAPlatform.java:439)
                         E      at com.gameanalytics.sdk.GAPlatform.loadIMEI(GAPlatform.java:407)
                         E      at com.gameanalytics.sdk.GAPlatform.setGoogleAID(GAPlatform.java:660)
                         E      at com.gameanalytics.sdk.GetGoogleAIDAsync.onPostExecute(GetGoogleAIDAsync.java:85)
                         E      at android.os.AsyncTask.finish(AsyncTask.java:695)
                         E      at android.os.AsyncTask.-wrap1(Unknown Source:0)
                         E      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7000)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                         E  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.ActivityCompat" on path: DexPathList[[zip file "/da
                            ta/app/com.thevogons.matchit-sz3-3xoiNTUyAp5honKlug==/base.apk"],nativeLibraryDirectories=[/data/app/com.thevogons.matchit-sz3-3xoiNTUyAp5
                            honKlug==/lib/arm, /data/app/com.thevogons.matchit-sz3-3xoiNTUyAp5honKlug==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
                         E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                         E      ... 13 more
```

**Comment by the1schwartz** [comment]
Thanks for reporting this. This should be fixed in the latest version now (v2.3.0)

**Comment by selimanac** [comment]
@the1schwartz Thank you. But v2.3.0 has a serious problem (Undefined symbols for architecture x86_64) See #24
